const Products={
    vegetables: {
        drumstick: { english: 'Drumstick', tamil: 'Murungai' },
        plantain: { english: 'Plantain', tamil: 'Vazhaikkai' },
        bananaFlower: { english: 'Banana Flower', tamil: 'Vazhaipoo' },
        snakeGourd: { english: 'Snake Gourd', tamil: 'Pudalangai' },
        bottleGourd: { english: 'Bottle Gourd', tamil: 'Sorakkai' },
        ashGourd: { english: 'Ash Gourd', tamil: 'Poosanikai' },
        brinjal: { english: 'Brinjal', tamil: 'Kathirikkai' },
        okra: { english: 'Okra', tamil: 'Vendakkai' },
        ridgeGourd: { english: 'Ridge Gourd', tamil: 'Peerkangai' },
        bitterGourd: { english: 'Bitter Gourd', tamil: 'Pavakkai' },
        clusterBeans: { english: 'Cluster Beans', tamil: 'Kothavarangai' },
        pumpkin: { english: 'Pumpkin', tamil: 'Parangikai' },
        taroRoot: { english: 'Taro Root', tamil: 'Seppankizhangu' },
        yam: { english: 'Yam', tamil: 'Senai Kizhangu' },
        beetroot: { english: 'Beetroot', tamil: 'Beetroot' },
        carrot: { english: 'Carrot', tamil: 'Carrot' },
        ladiesFinger: { english: 'Ladies Finger', tamil: 'Vendakkai' },
        tomato: { english: 'Tomato', tamil: 'Thakkali' },
        onion: { english: 'Onion', tamil: 'Vengayam' },
        potato: { english: 'Potato', tamil: 'Urulai Kizhangu' },
        radish: { english: 'Radish', tamil: 'Mooli' },
        greenPeas: { english: 'Green Peas', tamil: 'Pachai Pattani' },
        fenugreekSeeds: { english: 'Fenugreek Seeds', tamil: 'Vendhayam' },
        cauliflower: { english: 'Cauliflower', tamil: 'Phool Gobi' },
        cabbage: { english: 'Cabbage', tamil: 'Patta Gobi' },
        sweetPotato: { english: 'Sweet Potato', tamil: 'Sakkaravalli Kizhangu' },
        ginger: { english: 'Ginger', tamil: 'Inji' },
        garlic: { english: 'Garlic', tamil: 'Poondu' },
        greenChilies: { english: 'Green Chilies', tamil: 'Pachai Milagai' },
        capsicum: { english: 'Capsicum', tamil: 'Kuda Milagai' },
        turmeric: { english: 'Turmeric', tamil: 'Manjal' },
        beetGreens: { english: 'Beet Greens', tamil: 'Beetroot Keerai' },
        chayote: { english: 'Chayote', tamil: 'Chow Chow' },
        turnip: { english: 'Turnip', tamil: 'Aukai' },
        leek: { english: 'Leek', tamil: 'Vetrilai Poondu Thal' },
        celery: { english: 'Celery', tamil: 'Celery' },
        fennel: { english: 'Fennel', tamil: 'Perunjeerakam' },
        asafoetida: { english: 'Asafoetida', tamil: 'Perungayam' },
        ridgeGourdPeel: { english: 'Ridge Gourd Peel', tamil: 'Peerkangai Thol' },
        jackfruit: { english: 'Jackfruit', tamil: 'Palapazham' },
        whitePumpkin: { english: 'White Pumpkin', tamil: 'Vellai Poosanikai' },
        colocasia: { english: 'Colocasia', tamil: 'Seppankizhangu' },
        pointedGourd: { english: 'Pointed Gourd', tamil: 'Parwal' },
        blackEyedPeas: { english: 'Black-Eyed Peas', tamil: 'Karamani' },
        turai: { english: 'Turai', tamil: 'Turai' },
        elephantYam: { english: 'Elephant Yam', tamil: 'Senai Kizhangu' },
        clusterFig: { english: 'Cluster Fig', tamil: 'Attipazham' },
        ivyGourd: { english: 'Ivy Gourd', tamil: 'Kovakkai' },
        malabarSpinach: { english: 'Malabar Spinach', tamil: 'Basella (Basale) Keerai' },
        ridgeGourdSkin: { english: 'Ridge Gourd Skin', tamil: 'Peerkangai Thol Tharikkai' },
        drumstickSeeds: { english: 'Drumstick Seeds', tamil: 'Murungai Vitaikal' },
        springOnion: { english: 'Spring Onion', tamil: 'Vengaya Thal' },
        tamarind: { english: 'Tamarind', tamil: 'Puli' },
        rawMango: { english: 'Raw Mango', tamil: 'Maangaai' },
        brusselsSprouts: { english: 'Brussels Sprouts', tamil: 'Brussels Sprouts' },
        parsley: { english: 'Parsley', tamil: 'Kothamalli Ilai' },
        broccoli: { english: 'Broccoli', tamil: 'Broccoli' },
        yellowPumpkin: { english: 'Yellow Pumpkin', tamil: 'Manjal Poosanikai' },
        cucumber: { english: 'Cucumber', tamil: 'Vellarikai' },
        redCabbage: { english: 'Red Cabbage', tamil: 'Sivappu Mutta Kose' },
        pumpkinFlower: { english: 'Pumpkin Flower', tamil: 'Parangikai Poo' },
      },
      greens: {
        curryLeaves: { english: 'Curry Leaves', tamil: 'Kariveppilai' },
        fenugreekLeaves: { english: 'Fenugreek Leaves', tamil: 'Vendhaya Keerai' },
        spinach: { english: 'Spinach', tamil: 'Keerai' },
        coriander: { english: 'Coriander', tamil: 'Kothamalli' },
        mint: { english: 'Mint', tamil: 'Pudina' },
        amaranthLeaves: { english: 'Amaranth Leaves', tamil: 'Arai Keerai' },
        drumstickLeaves: { english: 'Drumstick Leaves', tamil: 'Murungai Keerai' },
        colocasiaLeaves: { english: 'Colocasia Leaves', tamil: 'Seppankizhangu Keerai' },
        mustardGreens: { english: 'Mustard Greens', tamil: 'Kadugu Keerai' },
        palak: { english: 'Palak', tamil: 'Palak Keerai' },
        watercress: { english: 'Watercress', tamil: 'Vallarai Keerai' },
        radishGreens: { english: 'Radish Greens', tamil: 'Mooli Keerai' },
        sorrelLeaves: { english: 'Sorrel Leaves', tamil: 'Pulicha Keerai' },
        fenugreekMicrogreens: { english: 'Fenugreek Microgreens', tamil: 'Vendhaya Microgreens' },
        mintMicrogreens: { english: 'Mint Microgreens', tamil: 'Pudina Microgreens' },
        corianderMicrogreens: { english: 'Coriander Microgreens', tamil: 'Kothamalli Microgreens' },
        mustardMicrogreens: { english: 'Mustard Microgreens', tamil: 'Kadugu Microgreens' },
        radishMicrogreens: { english: 'Radish Microgreens', tamil: 'Mooli Microgreens' },
        kale: { english: 'Kale', tamil: 'Kale' },
        swissChard: { english: 'Swiss Chard', tamil: 'Swiss Chard' },
        dillLeaves: { english: 'Dill Leaves', tamil: 'Sada Suvai' },
        lemongrass: { english: 'Lemongrass', tamil: 'Elumichai Pul' },
        chineseCabbage: { english: 'Chinese Cabbage', tamil: 'Chinese Cabbage' },
        kaleMicrogreens: { english: 'Kale Microgreens', tamil: 'Kale Microgreens' },
        swissChardMicrogreens: { english: 'Swiss Chard Microgreens', tamil: 'Swiss Chard Microgreens' },
        waterSpinach: { english: 'Water Spinach', tamil: 'Thootuvalai Keerai' },
        lambSQuarters: { english: "Lamb's Quarters", tamil: 'Thandu Keerai' },
        sweetPotatoLeaves: { english: 'Sweet Potato Leaves', tamil: 'Sakkaravalli Keerai' },
        colocasiaLeavesStem: { english: 'Colocasia Leaves Stem', tamil: 'Seppankizhangu Thandu' },
        greenSorrel: { english: 'Green Sorrel', tamil: 'Pulicha Keerai (Pachai Puliyanki)' },
        hibiscusLeaves: { english: 'Hibiscus Leaves', tamil: 'Sembaruthi Ilai' },
        greenAmaranth: { english: 'Green Amaranth', tamil: 'Siru Keerai' },
        papayaLeaves: { english: 'Papaya Leaves', tamil: 'Papali Ilai' },
        radishLeaves: { english: 'Radish Leaves', tamil: 'Mooli Keerai' },
        sunflowerMicrogreens: { english: 'Sunflower Microgreens', tamil: 'Sooriyakathali Microgreens' },
        purslane: { english: 'Purslane', tamil: 'Paruppu Keerai' },
      },
      fruits: {
        apple: { english: 'Apple', tamil: 'Apple' },
        banana: { english: 'Banana', tamil: 'Vazhai Pazham' },
        mango: { english: 'Mango', tamil: 'Manga' },
        orange: { english: 'Orange', tamil: 'Orange' },
        guava: { english: 'Guava', tamil: 'Koyya Pazham' },
        papaya: { english: 'Papaya', tamil: 'Papali' },
        pineapple: { english: 'Pineapple', tamil: 'Ananas' },
        pomegranate: { english: 'Pomegranate', tamil: 'Madhulai' },
        watermelon: { english: 'Watermelon', tamil: 'Tarpoosani Pazham' },
        muskmelon: { english: 'Muskmelon', tamil: 'Mulam Pazham' },
        jackfruit: { english: 'Jackfruit', tamil: 'Palapazham' },
        kiwi: { english: 'Kiwi', tamil: 'Kiwi' },
        custardApple: { english: 'Custard Apple', tamil: 'Seetha Pazham' },
        passionFruit: { english: 'Passion Fruit', tamil: 'Passion Fruit' },
        dragonFruit: { english: 'Dragon Fruit', tamil: 'Dragon Fruit' },
        sapota: { english: 'Sapota', tamil: 'Sapota' },
        lychee: { english: 'Lychee', tamil: 'Lychee' },
        fig: { english: 'Fig', tamil: 'Athi Pazham' },
        peach: { english: 'Peach', tamil: 'Peach' },
        apricot: { english: 'Apricot', tamil: 'Apricot' },
        plum: { english: 'Plum', tamil: 'Plum' },
        coconut: { english: 'Coconut', tamil: 'Thengai' },
        avocado: { english: 'Avocado', tamil: 'Avocado' },
        custardApple: { english: 'Custard Apple', tamil: 'Seetha Pazham' },
        grape: { english: 'Grape', tamil: 'Drakshai' },
        lemon: { english: 'Lemon', tamil: 'Elumichai' },
        strawberry: { english: 'Strawberry', tamil: 'Strawberry' },
        raspberry: { english: 'Raspberry', tamil: 'Raspberry' },
        blueberry: { english: 'Blueberry', tamil: 'Blueberry' },
        blackberry: { english: 'Blackberry', tamil: 'Blackberry' },
        cherry: { english: 'Cherry', tamil: 'Cherry' },
        gooseberry: { english: 'Gooseberry', tamil: 'Nellikai' },
        date: { english: 'Date', tamil: 'Pericham Pazham' },
        blackCurrant: { english: 'Black Currant', tamil: 'Black Currant' },
      },
      oils: {
        coconutOil: { english: 'Coconut Oil', tamil: 'Thengai Ennai' },
        sesameOil: { english: 'Sesame Oil', tamil: 'Ellu Ennai' },
        groundnutOil: { english: 'Groundnut Oil', tamil: 'Kadalai Ennai' },
        oliveOil: { english: 'Olive Oil', tamil: 'Olive Ennai' },
        sunflowerOil: { english: 'Sunflower Oil', tamil: 'Surya Flower Ennai' },
        canolaOil: { english: 'Canola Oil', tamil: 'Canola Ennai' },
        mustardOil: { english: 'Mustard Oil', tamil: 'Kadugu Ennai' },
        palmOil: { english: 'Palm Oil', tamil: 'Palm Ennai' },
        safflowerOil: { english: 'Safflower Oil', tamil: 'Safflower Ennai' },
        flaxseedOil: { english: 'Flaxseed Oil', tamil: 'Ali Vidhai Ennai' },
        soybeanOil: { english: 'Soybean Oil', tamil: 'Soya Ennai' },
        cornOil: { english: 'Corn Oil', tamil: 'Mokka Ennai' },
        almondOil: { english: 'Almond Oil', tamil: 'Badam Ennai' },
        walnutOil: { english: 'Walnut Oil', tamil: 'Walnut Ennai' },
        grapeseedOil: { english: 'Grapeseed Oil', tamil: 'Drakshai Vidhai Ennai' },
        riceBranOil: { english: 'Rice Bran Oil', tamil: 'Arisi Ennai' },
        avocadoOil: { english: 'Avocado Oil', tamil: 'Avocado Ennai' },
        hazelnutOil: { english: 'Hazelnut Oil', tamil: 'Hazelnut Ennai' },
        pumpkinSeedOil: { english: 'Pumpkin Seed Oil', tamil: 'Parangikai Vithai Ennai' },
        arganOil: { english: 'Argan Oil', tamil: 'Argan Ennai' },
        macadamiaNutOil: { english: 'Macadamia Nut Oil', tamil: 'Macadamia Nut Ennai' },
        pistachioOil: { english: 'Pistachio Oil', tamil: 'Pistachio Ennai' },
        camelinaOil: { english: 'Camelina Oil', tamil: 'Camelina Ennai' },
        blackCurrantSeedOil: { english: 'Black Currant Seed Oil', tamil: 'Black Currant Vidhai Ennai' },
        eveningPrimroseOil: { english: 'Evening Primrose Oil', tamil: 'Evening Primrose Ennai' },
        hempseedOil: { english: 'Hempseed Oil', tamil: 'Hempseed Ennai' },
        pecanOil: { english: 'Pecan Oil', tamil: 'Pecan Ennai' },
        poppySeedOil: { english: 'Poppy Seed Oil', tamil: 'Khasa Khasa Vidhai Ennai' },
        tamanuOil: { english: 'Tamanu Oil', tamil: 'Tamanu Ennai' },
        apricotKernelOil: { english: 'Apricot Kernel Oil', tamil: 'Apricot Kernel Ennai' },
      },
      rices: {
        basmatiRice: { english: 'Basmati Rice', tamil: 'Basmati Arisi' },
        ponniRice: { english: 'Ponni Rice', tamil: 'Ponni Arisi' },
        sonaMasooriRice: { english: 'Sona Masoori Rice', tamil: 'Sona Masoori Arisi' },
        mattaRice: { english: 'Matta Rice', tamil: 'Matta Arisi' },
        redRice: { english: 'Red Rice', tamil: 'Sigappu Arisi' },
        brownRice: { english: 'Brown Rice', tamil: 'Pacharisi' },
        idliRice: { english: 'Idli Rice', tamil: 'Idli Arisi' },
        parboiledRice: { english: 'Parboiled Rice', tamil: 'Puzhungal Arisi' },
        jasmineRice: { english: 'Jasmine Rice', tamil: 'Jasmine Arisi' },
        blackRice: { english: 'Black Rice', tamil: 'Karuppu Arisi' },
        seeragaSambaRice: { english: 'Seeraga Samba Rice', tamil: 'Seeraga Samba Arisi' },
        bambooRice: { english: 'Bamboo Rice', tamil: 'Moongil Arisi' },
        chambaRice: { english: 'Chamba Rice', tamil: 'Chamba Arisi' },
        jeerakasalaRice: { english: 'Jeerakasala Rice', tamil: 'Jeerakasala Arisi' },
      },
      pulses: {
        toorDal: { english: 'Toor Dal', tamil: 'Thuvaram Paruppu' },
        moongDal: { english: 'Moong Dal', tamil: 'Pasi Paruppu' },
        uradDal: { english: 'Urad Dal', tamil: 'Ulutham Paruppu' },
        chanaDal: { english: 'Chana Dal', tamil: 'Kadalai Paruppu' },
        masoorDal: { english: 'Masoor Dal', tamil: 'Masoor Paruppu' },
        redLentils: { english: 'Red Lentils', tamil: 'Sigappu Paruppu' },
        blackGramDal: { english: 'Black Gram Dal', tamil: 'Karuppu Ulutham Paruppu' },
        greenGramDal: { english: 'Green Gram Dal', tamil: 'Pachai Payaru Paruppu' },
        horseGram: { english: 'Horse Gram', tamil: 'Kollu' },
        mothBeans: { english: 'Moth Beans', tamil: 'Muthira' },
        rajma: { english: 'Rajma', tamil: 'Rajma' },
        cowpeas: { english: 'Cowpeas', tamil: 'Karamani' },
        blackEyedPeas: { english: 'Black-Eyed Peas', tamil: 'Karamani' },
        chickpeas: { english: 'Chickpeas', tamil: 'Kondakadalai' },
        greenPeas: { english: 'Green Peas', tamil: 'Pachai Pattani' },
        soybeans: { english: 'Soybeans', tamil: 'Soiya Vithai' },
        kidneyBeans: { english: 'Kidney Beans', tamil: 'Vellai Rajma' },
        greenLentils: { english: 'Green Lentils', tamil: 'Pachai Paruppu' },
        blackLentils: { english: 'Black Lentils', tamil: 'Karuppu Paruppu' },
      },
      spices: {
        mustardSeeds: { english: 'Mustard Seeds', tamil: 'Kadugu' },
        cuminSeeds: { english: 'Cumin Seeds', tamil: 'Jeeragam' },
        fennelSeeds: { english: 'Fennel Seeds', tamil: 'Perunjeerakam' },
        corianderSeeds: { english: 'Coriander Seeds', tamil: 'Kothamalli Vithai' },
        fenugreekSeeds: { english: 'Fenugreek Seeds', tamil: 'Vendhayam' },
        nigellaSeeds: { english: 'Nigella Seeds', tamil: 'Karunjeeragam' },
        poppySeeds: { english: 'Poppy Seeds', tamil: 'Khasa Khasa' },
        sesameSeeds: { english: 'Sesame Seeds', tamil: 'Ellu' },
        ajwain: { english: 'Ajwain', tamil: 'Omam' },
        asafoetida: { english: 'Asafoetida', tamil: 'Perungayam' },
        cinnamon: { english: 'Cinnamon', tamil: 'Pattai' },
        cardamom: { english: 'Cardamom', tamil: 'Elakka' },
        clove: { english: 'Clove', tamil: 'Krambu' },
        blackPepper: { english: 'Black Pepper', tamil: 'Milagu' },
        whitePepper: { english: 'White Pepper', tamil: 'Vellai Milagu' },
        cayennePepper: { english: 'Cayenne Pepper', tamil: 'Milagu Thool' },
        turmeric: { english: 'Turmeric', tamil: 'Manjal' },
        redChiliPowder: { english: 'Red Chili Powder', tamil: 'Sigappu Milagai Podi' },
        paprika: { english: 'Paprika', tamil: 'Paprika' },
        nutmeg: { english: 'Nutmeg', tamil: 'Jathikai' },
        mace: { english: 'Mace', tamil: 'Jathipathri' },
        bayLeaves: { english: 'Bay Leaves', tamil: 'Brinji Elai' },
        curryLeaves: { english: 'Curry Leaves', tamil: 'Kariveppilai' },
        tamarind: { english: 'Tamarind', tamil: 'Puli' },
        amchurPowder: { english: 'Amchur Powder', tamil: 'Amchur Podi' },
        garamMasala: { english: 'Garam Masala', tamil: 'Garam Masala' },
        chaatMasala: { english: 'Chaat Masala', tamil: 'Chaat Masala' },
      },
      seeds: {
        flaxseeds: { english: 'Flaxseeds', tamil: 'Ali Vithai' },
        chiaSeeds: { english: 'Chia Seeds', tamil: 'Chia Vithai' },
        pumpkinSeeds: { english: 'Pumpkin Seeds', tamil: 'Parangikai Vithai' },
        sunflowerSeeds: { english: 'Sunflower Seeds', tamil: 'Sooriyakathali Vithai' },
        sesameSeeds: { english: 'Sesame Seeds', tamil: 'Ellu' },
        watermelonSeeds: { english: 'Watermelon Seeds', tamil: 'Tarpoosani Vithai' },
        cucumberSeeds: { english: 'Cucumber Seeds', tamil: 'Vellarikai Vithai' },
        fennelSeeds: { english: 'Fennel Seeds', tamil: 'Perunjeerakam' },
        cuminSeeds: { english: 'Cumin Seeds', tamil: 'Jeeragam' },
      },
      seasonings: {
        mustardOil: { english: 'Mustard Oil', tamil: 'Kadugu Ennai' },
        curryLeaves: { english: 'Curry Leaves', tamil: 'Kariveppilai' },
        asafoetida: { english: 'Asafoetida', tamil: 'Perungayam' },
        fenugreekSeeds: { english: 'Fenugreek Seeds', tamil: 'Vendhayam' },
        cuminSeeds: { english: 'Cumin Seeds', tamil: 'Jeeragam' },
        mustardSeeds: { english: 'Mustard Seeds', tamil: 'Kadugu' },
        uradDal: { english: 'Urad Dal', tamil: 'Ulutham Paruppu' },
        chanaDal: { english: 'Chana Dal', tamil: 'Kadalai Paruppu' },
        blackPepper: { english: 'Black Pepper', tamil: 'Milagu' },
        cuminPowder: { english: 'Cumin Powder', tamil: 'Jeeragam Podi' },
        corianderPowder: { english: 'Coriander Powder', tamil: 'Kothamalli Podi' },
        garamMasala: { english: 'Garam Masala', tamil: 'Garam Masala' },
        turmericPowder: { english: 'Turmeric Powder', tamil: 'Manjal Podi' },
        redChiliPowder: { english: 'Red Chili Powder', tamil: 'Sigappu Milagai Podi' },
        sambarPowder: { english: 'Sambar Powder', tamil: 'Sambar Podi' },
        tamarind: { english: 'Tamarind', tamil: 'Puli' },
        jaggery: { english: 'Jaggery', tamil: 'Vellam' },
        salt: { english: 'Salt', tamil: 'Uppu' },
      },
      flours: {
        riceFlour: { english: 'Rice Flour', tamil: 'Arisi Maavu' },
        wheatFlour: { english: 'Wheat Flour', tamil: 'Godhumai Maavu' },
        gramFlour: { english: 'Gram Flour', tamil: 'Kadalamaavu' },
        semolina: { english: 'Semolina', tamil: 'Ravai' },
        milletFlour: { english: 'Millet Flour', tamil: 'Siru Thaniyam Maavu' },
        chickpeaFlour: { english: 'Chickpea Flour', tamil: 'Kondakadalai Maavu' },
        sorghumFlour: { english: 'Sorghum Flour', tamil: 'Cholam Maavu' },
        pearlMilletFlour: { english: 'Pearl Millet Flour', tamil: 'Kambu Maavu' },
        fingerMilletFlour: { english: 'Finger Millet Flour', tamil: 'Ragi Maavu' },
        cornFlour: { english: 'Corn Flour', tamil: 'Makka Cholam Maavu' },
        tapiocaFlour: { english: 'Tapioca Flour', tamil: 'Maravalli Kizhangu Maavu' },
        chestnutFlour: { english: 'Chestnut Flour', tamil: 'Varaka Maavu' },
        acornFlour: { english: 'Acorn Flour', tamil: 'Porichangai Maavu' },
      },
      meats: {
        chicken: { english: 'Chicken', tamil: 'Kozhi' },
        mutton: { english: 'Mutton', tamil: 'Aatu Kari' },
        beef: { english: 'Beef', tamil: 'Irachchi' },
        pork: { english: 'Pork', tamil: 'Sukuta' },
        fish: { english: 'Fish', tamil: 'Meen' },
        prawns: { english: 'Prawns', tamil: 'Eral' },
        crab: { english: 'Crab', tamil: 'Nandu' },
        lobster: { english: 'Lobster', tamil: 'Kozhi Eraal' },
        squid: { english: 'Squid', tamil: 'Kanava' },
        octopus: { english: 'Octopus', tamil: 'Koonthal' },
        turkey: { english: 'Turkey', tamil: 'Tanga Kozhi' },
        quail: { english: 'Quail', tamil: 'Kaadai' },
        duck: { english: 'Duck', tamil: 'Thari Kozhi' },
        rabbit: { english: 'Rabbit', tamil: 'Moolai Kozhi' },
        venison: { english: 'Venison', tamil: 'Māṉ Kari' },
      },
      dairy: {
        milk: { english: 'Milk', tamil: 'Paal' },
        curd: { english: 'Curd', tamil: 'Thayir' },
        butter: { english: 'Butter', tamil: 'Vennai' },
        ghee: { english: 'Ghee', tamil: 'Nei' },
        paneer: { english: 'Paneer', tamil: 'Paneer' },
        yogurt: { english: 'Yogurt', tamil: 'Yogurt' },
        cheese: { english: 'Cheese', tamil: 'Cheese' },
        buttermilk: { english: 'Buttermilk', tamil: 'Neer Mor' },
        condensedMilk: { english: 'Condensed Milk', tamil: 'Mitha Paal' },
        evaporatedMilk: { english: 'Evaporated Milk', tamil: 'Evaporated Paal' },
        sourCream: { english: 'Sour Cream', tamil: 'Sour Cream' },
        cream: { english: 'Cream', tamil: 'Cream' },
        ricottaCheese: { english: 'Ricotta Cheese', tamil: 'Ricotta Cheese' },
      },
}